RuxoACC = {

	AdminControl = false, -- Extra protection

    Local = "en", -- it,es,fr,en,de...

	GetVehicleFromConfig = false, --if false the menu get all veh models, true only veh from ListedVehicle and modVehicle inside config

	--Open Menu Request log
	WebhookRuxo= "",
	--Open Resource List log
	WebhookRuxoRes= "",
	--Give Item log
	WebhookRuxoIT= "",
	--Open Veh List log
	WebhookRuxoVEH= "",
	--SetJOB log
	WebhookRuxoJOB= "",
	
    --Enable admin list with AdminControl option
	BypassAdmin = { 
		"steam:", 
		"discord:",
	},

	--IT
	Translate = {
		fix_vehicle = "Ripara Veicolo",
		trainer = "Trainer",
		list_player = "Lista Player",
		list_vehicles = "Lista Veicoli",
		list_resource = "Lista Risorse",
		list_items = "Lista Item",
		clean = "Pulisci Area",
		jobs = "Lista Lavori",
		custom_vehicles = "Veicoli Custom",
		search = "Cerca",
		select_grade= "Scegli Grado",
		inv= "Invisibile",
		god_mode= "God Mode",
		revive = "Rianima",
		stop_res = "Risorse Stoppate",
		search_it = "Cerca Item",
		search_car = "Cerca Auto",
		qnt = "Quantità",
		done = "Eseguito",
		not_in = "Non sei in un veicolo",
		cant = "Non sei autorizzato",
		msg = "Messaggio inviato",
		area = "Area Pulita",
		job_set = "Lavoro impostato",
		blip_on = "Blips Attivati",
		blip_off = "Blips Disattivati",
		veh = "Veicoli",
		stop = "Risorse Stoppate",
		del_veh = "Elimina Veicolo",
		del_ped = "Elimina ped",
		del_prop = "Elimina prop",
		range = "Seleziona Range",
	},
	--EN
	TranslateEN = {
		fix_vehicle = "Repair Vehicle",
		trainer = "Trainer",
		list_player = "Player List",
		list_vehicles = "Vehicle List",
		list_resource = "Resource List",
		list_items = "Item List",
		clean = "Clean Area",
		jobs = "Job List",
		custom_vehicles = "Custom Vehicles",
		search = "Search",
		select_grade = "Select Grade",
		inv = "Invisible",
		god_mode = "God Mode",
		revive = "Revive",
		stop_res = "Stop Resources",
		search_it = "Search Item",
		search_car = "Search Car",
		qnt = "Quantity",
		done = "Done",
		not_in = "You are not in a vehicle",
		cant = "You are not authorized",
		msg = "Message sent",
		area = "Area Cleaned",
		job_set = "Job set",
		blip_on = "Blips Activated",
		blip_off = "Blips Deactivated",
		veh = "Vehicles",
		stop = "Stop Resources",
		del_veh = "Delete Vehicle",
		del_ped = "Delete Ped",
		del_prop = "Delete Prop",
		range = "Select Range",
	},

	TranslateFR = {
		fix_vehicle = "Réparer Véhicule",
		trainer = "Entraîneur",
		list_player = "Liste des Joueurs",
		list_vehicles = "Liste des Véhicules",
		list_resource = "Liste des Ressources",
		list_items = "Liste des Objets",
		clean = "Nettoyer la Zone",
		jobs = "Liste des Emplois",
		custom_vehicles = "Véhicules Personnalisés",
		search = "Rechercher",
		select_grade = "Sélectionner un Grade",
		inv = "Invisible",
		god_mode = "Mode Dieu",
		revive = "Réanimer",
		stop_res = "Arrêter les Ressources",
		search_it = "Rechercher un Objet",
		search_car = "Rechercher une Voiture",
		qnt = "Quantité",
		done = "Terminé",
		not_in = "Vous n'êtes pas dans un véhicule",
		cant = "Vous n'êtes pas autorisé",
		msg = "Message envoyé",
		area = "Zone Nettoyée",
		job_set = "Emploi défini",
		blip_on = "Blips Activés",
		blip_off = "Blips Désactivés",
		veh = "Véhicules",
		stop = "Arrêter les Ressources",
		del_veh = "Supprimer le Véhicule",
		del_ped = "Supprimer le Ped",
		del_prop = "Supprimer le Prop",
		range = "Choisir Range",
	},

	TranslateES = {
		fix_vehicle = "Reparar Vehículo",
		trainer = "Entrenador",
		list_player = "Lista de Jugadores",
		list_vehicles = "Lista de Vehículos",
		list_resource = "Lista de Recursos",
		list_items = "Lista de Objetos",
		clean = "Limpiar Área",
		jobs = "Lista de Trabajos",
		custom_vehicles = "Vehículos Personalizados",
		search = "Buscar",
		select_grade = "Seleccionar Grado",
		inv = "Invisible",
		god_mode = "Modo Dios",
		revive = "Revivir",
		stop_res = "Detener Recursos",
		search_it = "Buscar Objeto",
		search_car = "Buscar Auto",
		qnt = "Cantidad",
		done = "Hecho",
		not_in = "No estás en un vehículo",
		cant = "No tienes autorización",
		msg = "Mensaje enviado",
		area = "Área Limpia",
		job_set = "Trabajo configurado",
		blip_on = "Marcadores Activados",
		blip_off = "Marcadores Desactivados",
		veh = "Vehículos",
		stop = "Detener Recursos",
		del_veh = "Eliminar Vehículo",
		del_ped = "Eliminar Personaje",
		del_prop = "Eliminar Propiedad",
		range = "Escoger Range",
	},

	TranslateDE = {
		fix_vehicle = "Fahrzeug reparieren",
		trainer = "Trainer",
		list_player = "Spielerliste",
		list_vehicles = "Fahrzeugliste",
		list_resource = "Ressourcenliste",
		list_items = "Objektliste",
		clean = "Bereich säubern",
		jobs = "Jobliste",
		custom_vehicles = "Benutzerdefinierte Fahrzeuge",
		search = "Suchen",
		select_grade = "Grad auswählen",
		inv = "Unsichtbar",
		god_mode = "God-Modus",
		revive = "Wiederbeleben",
		stop_res = "Ressourcen stoppen",
		search_it = "Objekt suchen",
		search_car = "Auto suchen",
		qnt = "Menge",
		done = "Fertig",
		not_in = "Du befindest dich nicht in einem Fahrzeug",
		cant = "Du bist nicht autorisiert",
		msg = "Nachricht gesendet",
		area = "Bereich gereinigt",
		job_set = "Job festgelegt",
		blip_on = "Blips aktiviert",
		blip_off = "Blips deaktiviert",
		veh = "Fahrzeuge",
		stop = "Ressourcen stoppen",
		del_veh = "Fahrzeug löschen",
		del_ped = "Ped löschen",
		del_prop = "Objekt löschen",
		range = "Auswählen Range",
	},

	ListedVehicle = {
		"adder",
		"Airbus",
		"Airtug",
		"akula",
		"akuma",
		"alkonost",
		"alpha",
		"alphaz1",
		"ambulance",
		"annihilator",
		"annihilator2",
		"apc",
		"arbitergt",
		"ardent",
		"armytanker",
		"armytrailer",
		"armytrailer2",
		"asbo",
		"asea",
		"asea2",
		"asterope",
		"astron",
		"astron2",
		"autarch",
		"avarus",
		"avenger",
		"avenger2",
		"avisa",
		"bagger",
		"baletrailer",
		"Baller",
		"baller2",
		"baller3",
		"baller4",
		"baller5",
		"baller6",
		"baller7",
		"banshee",
		"banshee2",
		"BARRACKS",
		"BARRACKS2",
		"BARRACKS3",
		"barrage",
		"bati",
		"bati2",
		"Benson",
		"besra",
		"bestiagts",
		"bf400",
		"BfInjection",
		"Biff",
		"bifta",
		"bison",
		"Bison2",
		"Bison3",
		"BjXL",
		"blade",
		"blazer",
		"blazer2",
		"blazer3",
		"blazer4",
		"blazer5",
		--[[ "BLIMP",
		"BLIMP2",
		"blimp3", ]]
		"blista",
		"blista2",
		"blista3",
		"BMX",
		"boattrailer",
		"bobcatXL",
		"Bodhi2",
		"bombushka",
		"boxville",
		"boxville2",
		"boxville3",
		"boxville4",
		"boxville5",
		"brawler",
		"brickade",
		"brioso",
		"brioso2",
		"brioso3",
		"bruiser",
		"bruiser2",
		"bruiser3",
		"brutus",
		"brutus2",
		"brutus3",
		"btype",
		"btype2",
		"btype3",
		"buccaneer",
		"buccaneer2",
		"buffalo",
		"buffalo2",
		"buffalo3",
		"buffalo4",
		"bulldozer",
		"bullet",
		"Burrito",
		"burrito2",
		"burrito3",
		"Burrito4",
		"burrito5",
		"BUS",
		"buzzard",
		"Buzzard2",
		"cablecar",
		"caddy",
		"Caddy2",
		"caddy3",
		"calico",
		"CAMPER",
		"caracara",
		"caracara2",
		"carbonizzare",
		"carbonrs",
		"Cargobob",
		"cargobob2",
		"Cargobob3",
		"Cargobob4",
		"cargoplane",
		"casco",
		"cavalcade",
		"cavalcade2",
		"cerberus",
		"cerberus2",
		"cerberus3",
		"champion",
		"cheburek",
		"cheetah",
		"cheetah2",
		"chernobog",
		"chimera",
		"chino",
		"chino2",
		"cinquemila",
		"cliffhanger",
		"clique",
		"club",
		"coach",
		"cog55",
		"cog552",
		"cogcabrio",
		"cognoscenti",
		"cognoscenti2",
		"comet2",
		"comet3",
		"comet4",
		"comet5",
		"comet6",
		"comet7",
		"conada",
		"contender",
		"coquette",
		"coquette2",
		"coquette3",
		"coquette4",
		"corsita",
		"cruiser",
		"CRUSADER",
		"cuban800",
		"cutter",
		"cyclone",
		"cyclone2",
		"cypher",
		"daemon",
		"daemon2",
		"deathbike",
		"deathbike2",
		"deathbike3",
		"defiler",
		"deity",
		"deluxo",
		"deveste",
		"deviant",
		"diablous",
		"diablous2",
		"dilettante",
		"dilettante2",
		"Dinghy",
		"dinghy2",
		"dinghy3",
		"dinghy4",
		"dinghy5",
		"dloader",
		"docktrailer",
		"docktug",
		"dodo",
		"Dominator",
		"dominator2",
		"dominator3",
		"dominator4",
		"dominator5",
		"dominator6",
		"dominator7",
		"dominator8",
		"double",
		"drafter",
		"draugur",
		"dubsta",
		"dubsta2",
		"dubsta3",
		"dukes",
		"dukes2",
		"dukes3",
		"dump",
		"dune",
		"dune2",
		"dune3",
		"dune4",
		"dune5",
		"duster",
		"Dynasty",
		"elegy",
		"elegy2",
		"ellie",
		"emerus",
		"emperor",
		"Emperor2",
		"emperor3",
		"enduro",
		"entity2",
		"entityxf",
		"esskey",
		"Euros",
		"everon",
		"exemplar",
		"f620",
		"faction",
		"faction2",
		"faction3",
		"fagaloa",
		"faggio",
		"faggio2",
		"faggio3",
		"FBI",
		"FBI2",
		"fcr",
		"fcr2",
		"felon",
		"felon2",
		"feltzer2",
		"feltzer3",
		"firetruk",
		"fixter",
		"flashgt",
		"FLATBED",
		"fmj",
		"FORKLIFT",
		"formula",
		"formula2",
		"fq2",
		"freecrawler",
		"freight",
		"freightcar",
		"freightcar2",
		"freightcont1",
		"freightcont2",
		"freightgrain",
		"freighttrailer",
		"Frogger",
		"frogger2",
		"fugitive",
		"furia",
		"furoregt",
		"fusilade",
		"futo",
		"futo2",
		"gargoyle",
		"Gauntlet",
		"gauntlet2",
		"gauntlet3",
		"gauntlet4",
		"gauntlet5",
		"gb200",
		"gburrito",
		"gburrito2",
		"glendale",
		"glendale2",
		"gp1",
		"graintrailer",
		"GRANGER",
		"granger2",
		"greenwood",
		"gresley",
		"growler",
		"gt500",
		"guardian",
		"habanero",
		"hakuchou",
		"hakuchou2",
		"halftrack",
		"handler",
		"Hauler",
		"Hauler2",
		"havok",
		"hellion",
		"hermes",
		"hexer",
		"hotknife",
		"hotring",
		"howard",
		"hunter",
		"huntley",
		"hustler",
		"hydra",
		"ignus",
		"ignus2",
		"imorgon",
		"impaler",
		"impaler2",
		"impaler3",
		"impaler4",
		"imperator",
		"imperator2",
		"imperator3",
		"infernus",
		"infernus2",
		"ingot",
		"innovation",
		"insurgent",
		"insurgent2",
		"insurgent3",
		"intruder",
		"issi2",
		"issi3",
		"issi4",
		"issi5",
		"issi6",
		"issi7",
		"italigtb",
		"italigtb2",
		"italigto",
		"italirsx",
		"iwagen",
		"jackal",
		"jb700",
		"jb7002",
		"jester",
		"jester2",
		"jester3",
		"jester4",
		"jet",
		"jetmax",
		"journey",
		"jubilee",
		"jugular",
		"kalahari",
		"kamacho",
		"kanjo",
		"kanjosj",
		"khamelion",
		"khanjali",
		"komoda",
		"kosatka",
		"krieger",
		"kuruma",
		"kuruma2",
		"landstalker",
		"landstalker2",
		"Lazer",
		"le7b",
		"lectro",
		"lguard",
		"limo2",
		"lm87",
		"locust",
		"longfin",
		"lurcher",
		"luxor",
		"luxor2",
		"lynx",
		"mamba",
		"mammatus",
		"manana",
		"manana2",
		"manchez",
		"manchez2",
		"marquis",
		"marshall",
		"massacro",
		"massacro2",
		"maverick",
		"menacer",
		"MESA",
		"mesa2",
		"MESA3",
		"metrotrain",
		"michelli",
		"microlight",
		"Miljet",
		"minitank",
		"minivan",
		"minivan2",
		"Mixer",
		"Mixer2",
		"mogul",
		"molotok",
		"monroe",
		"monster",
		"monster3",
		"monster4",
		"monster5",
		"moonbeam",
		"moonbeam2",
		"Mower",
		"Mule",
		"Mule2",
		"Mule3",
		"mule4",
		"mule5",
		"nebula",
		"nemesis",
		"neo",
		"neon",
		"nero",
		"nero2",
		"nightblade",
		"nightshade",
		"nightshark",
		"nimbus",
		"ninef",
		"ninef2",
		"nokota",
		"Novak",
		"omnis",
		"omnisegt",
		"openwheel1",
		"openwheel2",
		"oppressor",
		"oppressor2",
		"oracle",
		"oracle2",
		"osiris",
		"outlaw",
		"Packer",
		"panto",
		"paradise",
		"paragon",
		"paragon2",
		"pariah",
		"patriot",
		"patriot2",
		"patriot3",
		"patrolboat",
		"pbus",
		"pbus2",
		"pcj",
		"penetrator",
		"penumbra",
		"penumbra2",
		"peyote",
		"peyote2",
		"peyote3",
		"pfister811",
		"Phantom",
		"phantom2",
		"phantom3",
		"Phoenix",
		"picador",
		"pigalle",
		"police",
		"police2",
		"police3",
		"police4",
		"policeb",
		"policeold1",
		"policeold2",
		"policet",
		"polmav",
		"pony",
		"pony2",
		"postlude",
		"Pounder",
		"pounder2",
		"prairie",
		"pRanger",
		"Predator",
		"premier",
		"previon",
		"primo",
		"primo2",
		"proptrailer",
		"prototipo",
		"pyro",
		"radi",
		"raiden",
		"raketrailer",
		"rallytruck",
		"RancherXL",
		"rancherxl2",
		"RapidGT",
		"RapidGT2",
		"rapidgt3",
		"raptor",
		"ratbike",
		"ratloader",
		"ratloader2",
		"rcbandito",
		"reaper",
		"Rebel",
		"rebel2",
		"rebla",
		"reever",
		"regina",
		"remus",
		"Rentalbus",
		"retinue",
		"retinue2",
		"revolter",
		"rhapsody",
		"rhinehart",
		"RHINO",
		"riata",
		"RIOT",
		"riot2",
		"Ripley",
		"rocoto",
		"rogue",
		"romero",
		"rrocket",
		"rt3000",
		"Rubble",
		"ruffian",
		"ruiner",
		"ruiner2",
		"ruiner3",
		"ruiner4",
		"rumpo",
		"rumpo2",
		"rumpo3",
		"ruston",
		"s80",
		"s95",
		"sabregt",
		"sabregt2",
		"Sadler",
		"sadler2",
		"Sanchez",
		"sanchez2",
		"sanctus",
		"sandking",
		"sandking2",
		"savage",
		"savestra",
		"sc1",
		"scarab",
		"scarab2",
		"scarab3",
		"schafter2",
		"schafter3",
		"schafter4",
		"schafter5",
		"schafter6",
		"schlagen",
		"schwarzer",
		"scorcher",
		"scramjet",
		"scrap",
		"seabreeze",
		"seashark",
		"seashark2",
		"seashark3",
		"seasparrow",
		"seasparrow2",
		"seasparrow3",
		"Seminole",
		"seminole2",
		"sentinel",
		"sentinel2",
		"sentinel3",
		"sentinel4",
		"serrano",
		"SEVEN70",
		"Shamal",
		"sheava",
		"SHERIFF",
		"sheriff2",
		"shinobi",
		"shotaro",
		"skylift",
		"slamtruck",
		"slamvan",
		"slamvan2",
		"slamvan3",
		"slamvan4",
		"slamvan5",
		"slamvan6",
		"sm722",
		"sovereign",
		"SPECTER",
		"SPECTER2",
		"speeder",
		"speeder2",
		"speedo",
		"speedo2",
		"speedo4",
		"squaddie",
		"squalo",
		"stafford",
		"stalion",
		"stalion2",
		"stanier",
		"starling",
		"stinger",
		"stingergt",
		"stockade",
		"stockade3",
		"stratum",
		"streiter",
		"stretch",
		"strikeforce",
		"stromberg",
		"Stryder",
		"Stunt",
		"submersible",
		"submersible2",
		"Sugoi",
		"sultan",
		"sultan2",
		"sultan3",
		"sultanrs",
		"Suntrap",
		"superd",
		"supervolito",
		"supervolito2",
		"Surano",
		"SURFER",
		"Surfer2",
		"surge",
		"swift",
		"swift2",
		"swinger",
		"t20",
		"Taco",
		"tailgater",
		"tailgater2",
		"taipan",
		"tampa",
		"tampa2",
		"tampa3",
		"tanker",
		"tanker2",
		"tankercar",
		"taxi",
		"technical",
		"technical2",
		"technical3",
		"tempesta",
		"tenf",
		"tenf2",
		"terbyte",
		"tezeract",
		"thrax",
		"thrust",
		"thruster",
		"tigon",
		"TipTruck",
		"TipTruck2",
		"titan",
		"toreador",
		"torero",
		"torero2",
		"tornado",
		"tornado2",
		"tornado3",
		"tornado4",
		"tornado5",
		"tornado6",
		"toro",
		"toro2",
		"toros",
		"TOURBUS",
		"TOWTRUCK",
		"Towtruck2",
		"tr2",
		"tr3",
		"tr4",
		"TRACTOR",
		"tractor2",
		"tractor3",
		"trailerlarge",
		"trailerlogs",
		"trailers",
		"trailers2",
		"trailers3",
		"trailers4",
		"trailersmall",
		"trailersmall2",
		"Trash",
		"trash2",
		"trflat",
		"tribike",
		"tribike2",
		"tribike3",
		"trophytruck",
		"trophytruck2",
		"tropic",
		"tropic2",
		"tropos",
		"tug",
		"tula",
		"tulip",
		"turismo2",
		"turismor",
		"tvtrailer",
		"tyrant",
		"tyrus",
		"utillitruck",
		"utillitruck2",
		"Utillitruck3",
		"vacca",
		"Vader",
		"vagner",
		"vagrant",
		"valkyrie",
		"valkyrie2",
		"vamos",
		"vectre",
		"velum",
		"velum2",
		"verlierer2",
		"verus",
		"vestra",
		"vetir",
		"veto",
		"veto2",
		"vigero",
		"vigero2",
		"vigilante",
		"vindicator",
		"virgo",
		"virgo2",
		"virgo3",
		"viseris",
		"visione",
		"volatol",
		"volatus",
		"voltic",
		"voltic2",
		"voodoo",
		"voodoo2",
		"vortex",
		"vstr",
		"warrener",
		"warrener2",
		"washington",
		"wastelander",
		"weevil",
		"weevil2",
		"windsor",
		"windsor2",
		"winky",
		"wolfsbane",
		"xa21",
		"xls",
		"xls2",
		"yosemite",
		"yosemite2",
		"yosemite3",
		"youga",
		"youga2",
		"youga3",
		"youga4",
		"z190",
		"zeno",
		"zentorno",
		"zhaba",
		"zion",
		"zion2",
		"zion3",
		"zombiea",
		"zombieb",
		"zorrusso",
		"zr350",
		"zr380",
		"zr3802",
		"zr3803",
		"Ztype",
	},

	ModVehicle = {
		"Coastline",
		"missile",
		"roxanne",
		"rs7c8beast",
		"rsq82ncs",
		"bmxBaby",
		"minia",
		"minib",
		"minic",
		"minid",
		"PV_bmwe36",
		"PV_bugatti",
		"PV_bugvr",
		"PV_dawn",
		"PV_gtr",
		"PV_jeep",
		"PV_lgss",
		"PV_rover",
		"PV_sianr",
		"PV_urus",
		"pantor",
		"mansm2",
		"m4vision",
		"rmodmi8lb",
		"rmodx6",
		"x6mf96lbwk",
		"bansheeas",
		"mesar",
		"coe54t",
		"charger69",
		"hentrx",
		"v4sp",
		"mh6",
		"812nlargo",
		"ApertaDRCustoM",
		"fer488beast",
		"gcmferraripurosangue",
		"mansroma",
		"pista",
		"sp3daytona",
		"126p",
		"panda",
		"rmodbiposto",
		"19raptor",
		"focusrs",
		"gtorino76",
		"rmodmustang",
		"sgt500",
		"sou_netzel450",
		"africat",
		"cbr1000rrr",
		"fk8hr",
		"hs2000",
		"zx10r",
		"agerarsc",
		"lp700r",
		"rmodlp670",
		"rmodlp770",
		"Tecnica",
		"urus",
		"lanciad",
		"rmodjeep",
		"rmodrover",
		"is300",
		"rx7",
		"fd",
		"sunrise1",
		"190e",
		"eqs22",
		"evcs65",
		"gcmgle63s2021",
		"gle63",
		"gxg63",
		"bnr32",
		"bnr34",
		"clubgtr",
		"er34",
		"lwgtr",
		"nadirs15",
		"r33",
		"r35prior",
		"argento",
		"wbgtx",
		"911r",
		"evo9",
		"p90d",
		"gxa90",
		"toysupmk4",
		"xp210",
		"bcatctx",
		"tmaxFW",
		"bearcat",
		"argentoc",
		"policeb2",
		"c3harley",
		"code3bmw",
		"code3fpis",
		"code318charg",
		"code318tahoe",
		"code320exp",
		"code398cvpi",
		"dominator31",
		"poldom",
		"swatinsur",
		"swatstoc",
		"swatvanr",
		"swatvanr2",
		"swatvans",
		"swatvans2",
		"f450ambo",
		"nkjugular",
		"nkjugularum"
	},

}